<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "livechatinc"
 *
 * Auto generated by Extension Builder 2017-05-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'LiveChat',
    'description' => 'LiveChat – live chat software and help desk software for customer service. Live chat allows website visitors to contact you in real-time. Help desk software is used to online visitors find what they need before they leave your site.
You can try LiveChat free for 30 days! If you are interested you can signup here: https://www.livechatinc.com/signup/
If you nev: http://www.livechatinc.com/why-livechat/
The extension requires active LiveChat subscription after 30 days of free trial.',
    'category' => 'services',
    'author' => 'Benjamin Riezler',
    'author_email' => 'typo3@pixel-ink.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
