<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "livechatinc"
 *
 * Auto generated by Extension Builder 2017-05-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Livechat Inc',
    'description' => 'Integrate the Live Chat from www.livechatinc.com in your TYPO3 Page. 
You need an an account created at https://www.livechatinc.com',
    'category' => 'services',
    'author' => 'Benjamin Riezler',
    'author_email' => 'typo3@pixel-ink.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
